name: MyGitHubActions

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Git
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: MyTest
      run: javac src/test/java/org/example/TestMin.java
