name: Tests

on:
  push:
  pull_request:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMin
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestMin
          if [ $? -eq 0 ]; then
            echo "successMin=true" >> $GITHUB_ENV
          else
            echo "successMin=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: TestMax
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestMax
          if [ $? -eq 0 ]; then
            echo "successMax=true" >> $GITHUB_ENV
          else
            echo "successMax=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: TestSum
        run: |
          mvn clean test -Dtest=org.example.TestSum
          if [ $? -eq 0 ]; then
            echo "successSum=true" >> $GITHUB_ENV
          else
            echo "successSum=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: TestMult
        run: |
          mvn clean test -Dtest=org.example.TestMult
          if [ $? -eq 0 ]; then
            echo "successMult=true" >> $GITHUB_ENV
          else
            echo "successMult=false" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: TestScan
        run: |
          mvn clean test -Dtest=org.example.MyTest
          testScan=$?

      - name: CheckUpTelegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"


      - name: qq
        run: echo $successScan

#      - name: CheckMin
#        if: "$successMin" = "false"
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: "TestMin не пройден"
#
#      - name: CheckMax
#        if: env.successMax == 'false'
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: "TestMax не пройден"
#
#      - name: CheckSum
#        if: env.successSum == 'false'
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: "TestSum не пройден"
#
#      - name: CheckMult
#        if: env.successMult == 'false'
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT_ID }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: "TestMult не пройден"
#
      - name: Check scanFile
        if: ${{ testScan != 0 }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestScanFile не пройден"