name: Tests

on:
  push:
  pull_request:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Test min
        run: mvn clean test -Dtest=org.example.TestMin

      - name: Test max
        run: mvn clean test -Dtest=org.example.TestMax

      - name: Test sum
        run: mvn clean test -Dtest=org.example.TestSum

      - name: Test mult
        run: mvn clean test -Dtest=org.example.TestMult

      - name: Test scanFile
        run: mvn clean test -Dtest=org.example.TestScanFile
