name: Tests
env:
  successMin: 'true'
  successMax: 'true'
  successSum: 'true'
  successMult: 'true'
  successScan: 'true'

on:
  push:
  pull_request:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMin
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestMin
          if grep -q 'FAILURES' target/surefire-reports/*.txt; then
          export successMin='false'
          exit 1
          fi
        continue-on-error: true

      - name: TestMax
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestMax
          if grep -q 'FAILURES' target/surefire-reports/*.txt; then
          export successMax='false'
          exit 1
          fi
        continue-on-error: true

      - name: TestSum
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestSum
          if grep -q 'FAILURES' target/surefire-reports/*.txt; then
          export successSum='false'
          exit 1
          fi
        continue-on-error: true

      - name: TestMult
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.TestMult
          if grep -q 'FAILURES' target/surefire-reports/*.txt; then
          export successMult='false'
          exit 1
          fi
        continue-on-error: true

      - name: TestScanFile
        run: |
          mvn clean test --fail-at-end -Dtest=org.example.MyTest
          if grep -q 'FAILURES' target/surefire-reports/*.txt; then
          export successScan='false'
          echo "kekekekekekekekekekekekekekekekkeekekekekekeke"
          exit 1
          fi
        continue-on-error: true

      - name: CheckUpTelegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"


      - name: qq
        run: echo $successMin

      - name: CheckMin
        if: env.successMin == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMin не пройден"

      - name: CheckMax
        if: env.successMax == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMax не пройден"

      - name: CheckSum
        if: env.successSum == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestSum не пройден"

      - name: CheckMult
        if: env.successMult == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMult не пройден"

      - name: Check scanFile
        if: env.successScan == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestScanFile не пройден"