name: GitHub Action

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21.0.2
      uses: actions/setup-java@v1
      with:
        java-version: '21.0.2'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Testing
      run: javac ~//UnitTests_v2.0/src/test/java/org/example/AppTest.java
