name: Tests

on:
  push:
  pull_request:

jobs:
  testingAll:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMin
        run: mvn clean test -Dtest=org.example.TestMin

      - name: TestMax
        run: mvn clean test -Dtest=org.example.TestMax

      - name: TestSum
        run: mvn clean test -Dtest=org.example.TestSum

      - name: TestMult
        run: mvn clean test -Dtest=org.example.TestMult

      - name: TestScan
        run: mvn clean test -Dtest=org.example.MyTest

      - name: CheckUpTelegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"

  testingMin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMin
        run: mvn clean test -Dtest=org.example.TestMin

      - name: CheckMin
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMin не пройден"

  testingMax:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMax
        run: mvn clean test -Dtest=org.example.TestMax

      - name: CheckMax
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMax не пройден"

  testingSum:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestSum
        run: mvn clean test -Dtest=org.example.TestSum

      - name: CheckSum
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestSum не пройден"

  testingMult:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMult
        run: mvn clean test -Dtest=org.example.TestMult

      - name: CheckMult
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestMult не пройден"

  testingScan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestScan
        run: mvn clean test -Dtest=org.example.MyTest

      - name: Check scanFile

        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "TestScanFile не пройден"